services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    environment:
      - APP_LEVEL=PROD
    command: bash /start.sh
    ports:
      - 3000:3000
    volumes:
      - ./configs:/project/configs
    networks:
      - webservice-network

  mongo:
    container_name: manager-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - webservice-network

networks:
  webservice-network:
    external:
      name: webservice-network
