services:
  app:
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - "$PWD/api:/project/api"
      - "$PWD/configs:/project/configs"
      - "$PWD/src:/app/src"
      - "$PWD/public:/app/public"
    environment:
      - APP_LEVEL=DEV
