services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jpyles0524/server-dashboard:latest
    container_name: dashboard
    environment:
      - APP_LEVEL=PROD
    command: bash /start.sh
    ports:
      - 3000:3000
    volumes:
      - ./configs:/project/configs
      - ./data:/project/data
