name: Push Docker Image

description: Push the Docker image to Docker Hub

inputs:
  gpat_token:
    description: The GitHub PAT token
    required: true
  dockerhub_username:
    description: The Docker Hub username
    required: true
  dockerhub_token:
    description: The Docker Hub token
    required: true
  dockerhub_repo:
    description: The Docker Hub repo
    required: true
  version:
    description: The version to update the project to
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.gpat_token }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set tag for docker image
      id: set_tag
      run: |
        if [ -z "${{ inputs.dockerhub_username }}" ] || [ -z "${{ inputs.dockerhub_repo }}" ] || [ -z "${{ inputs.version }}" ]; then
          echo "Error: Missing required input values!"
          exit 1
        fi
        TAG=${{ inputs.dockerhub_username }}/${{ inputs.dockerhub_repo }}:${{ inputs.version }}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Docker image tag is: $TAG"
      shell: bash

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.TAG }}
          ${{ inputs.dockerhub_username }}/${{ inputs.dockerhub_repo }}:latest
