name: Update Python project version

description: Updates the version in the pyproject.toml file

inputs:
  version:
    description: The version to update the project to
    required: true
  gpat_token:
    description: The GitHub PAT token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.gpat_token }}

    - name: Update pyproject.toml
      run: |
        sed -i "s/^version = \".*/version = \"${{ inputs.version }}\"/" pyproject.toml
      shell: bash

    - name: Commit changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add pyproject.toml
        git commit -m "Update version to ${{ inputs.version }} [skip ci]"
        git push
      shell: bash
