apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/jaypyles/helm-charts/main  
    chart: dashboard
    targetRevision: ">=1.0.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true