name: Push Docker Images

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Verify Doppler Token
      #   run: |
      #     if [ -z "$DOPPLER_TOKEN" ]; then
      #       echo "DOPPLER_TOKEN is not set"
      #       exit 1
      #     else
      #       echo "DOPPLER_TOKEN is set"
      #     fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKERHUB_REPO}}:latest
          build-args: DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}

      - name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKERHUB_API_REPO}}:latest
          build-args: DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}
