name: Release

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get semantic version
        uses: ./.github/actions/get-semantic-version
        with:
          gpat_token: ${{ secrets.GPAT_TOKEN }}

      - name: Update version of app
        uses: ./.github/actions/update-version
        with:
          version: $VERSION
          gpat_token: ${{ secrets.GPAT_TOKEN }}
          helm_url: ${{ secrets.HELM_URL }} 

      - name: Push Docker image
        uses: ./.github/actions/push-docker-image
        with:
          version: $VERSION
          gpat_token: ${{ secrets.GPAT_TOKEN }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub_repo: ${{ secrets.DOCKERHUB_REPO }}
